apiVersion: v1
kind: Namespace
metadata:
  name: csv
---
apiVersion: v1
kind: Service
metadata:
  name: csv-ui
  namespace: csv
spec:
  selector:
    app: csv-ui
  ports:
  - port: 8080
    targetPort: 80
---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-ui
  namespace: csv
  labels:
    app: csv-ui
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csv-ui
  template:
    metadata:
      labels:
        app: csv-ui
    spec:
      containers:
        - name: csv-ui
          resources:
            requests:
               cpu: 25m
               memory: 8Mi
            limits:
              cpu: 50m
              memory: 32Mi
          image:  csv:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80    
      restartPolicy: Always
 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: csv-ui
  namespace: csv
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/ssl-ciphers: "HIGH:!aNULL:!MD5"
  labels:
    name: csv-ui
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - csv.io
    - www.csv.io
    secretName: nginx1-ca-secret
  rules:
  - host: csv.io
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: csv-ui
            port:
              number: 8080
---