apiVersion: v1
kind: Namespace
metadata:
  name: csv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conservatoire
  namespace: csv
  labels:
    app: conservatoire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conservatoire
  template:
    metadata:
      labels:
        app: conservatoire
    spec:
      containers:
      - name: mysql
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Gi
       
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: root
          - name: MARIADB_DATABASE
            value: bd_saintviateur
        image: bd:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
     
---
apiVersion: v1
kind: Service
metadata:
  name: conservatoire
  namespace: csv
spec:
  selector:
    app: conservatoire
  ports:
  - port: 3306
    targetPort: 3306